<?php

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function migrate_custombsos_migrate_d7_node_fsprofile_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
    $values = $row->getSourceProperty('field_degrees_hel');
    $value_new = [];
    if ($values) {
      foreach ($values as $value) {
        $value_new[] = ['item_id' => $value['value']];
      }
      $row->setSourceProperty('field_degrees_held_new', $value_new);
    }
}
